"use client";

import { useState } from "react";
import { formatMoney } from "@/lib/money";
import { repeatLabel, type OverheadRepeat } from "@/lib/overhead-recurrence";
import { PencilIcon, RepeatIcon, TrashIcon } from "@/components/icons";
import { updateOverhead, deleteOverhead } from "@/app/actions/overheads";

export type CostItem = {
  id: number;
  dateInput: string;
  dateLabel: string;
  category: string;
  description: string;
  amount: number;
  recurrence: OverheadRepeat;
  /** True when this row was generated by a repeating cost. */
  isCopy: boolean;
};

export function CostList({
  items,
  categories,
  categoryColour,
}: {
  items: CostItem[];
  categories: Record<string, string>;
  categoryColour: Record<string, string>;
}) {
  return (
    <div className="card divide-y divide-stone-100">
      {items.map((item) => (
        <CostRow
          key={item.id}
          item={item}
          categories={categories}
          categoryColour={categoryColour}
        />
      ))}
    </div>
  );
}

function CostRow({
  item,
  categories,
  categoryColour,
}: {
  item: CostItem;
  categories: Record<string, string>;
  categoryColour: Record<string, string>;
}) {
  const [editing, setEditing] = useState(false);
  const repeats = item.recurrence !== "NONE";

  return (
    <div>
      <div className="flex items-center gap-3 px-4 py-3">
        <span className={`badge ${categoryColour[item.category]}`}>
          {categories[item.category]}
        </span>
        <div className="min-w-0 flex-1">
          <div className="truncate text-sm font-medium text-stone-800">
            {item.description || categories[item.category]}
          </div>
          <div className="flex items-center gap-1.5 text-xs text-stone-400">
            <span>{item.dateLabel}</span>
            {repeats && (
              <span className="inline-flex items-center gap-1 font-semibold text-brand-700">
                <RepeatIcon className="h-3 w-3" />
                {repeatLabel[item.recurrence]}
              </span>
            )}
            {item.isCopy && <span>· repeat</span>}
          </div>
        </div>
        <span className="text-sm font-semibold text-stone-800 tabular-nums">
          {formatMoney(item.amount)}
        </span>
        <button
          type="button"
          onClick={() => setEditing((v) => !v)}
          className="text-stone-300 hover:text-brand-700"
          aria-label={`Edit ${item.description || categories[item.category]}`}
          aria-expanded={editing}
        >
          <PencilIcon className="h-4 w-4" />
        </button>
        <form action={deleteOverhead}>
          <input type="hidden" name="id" value={item.id} />
          <button className="text-stone-300 hover:text-red-500" aria-label="Delete overhead">
            <TrashIcon className="h-4 w-4" />
          </button>
        </form>
      </div>

      {editing && (
        <form
          action={async (fd) => {
            await updateOverhead(fd);
            setEditing(false);
          }}
          className="grid gap-3 border-t border-stone-100 bg-stone-50 px-4 py-4 sm:grid-cols-2"
        >
          <input type="hidden" name="id" value={item.id} />
          <div>
            <label className="label">Category</label>
            <select
              name="category"
              className="input"
              defaultValue={item.category}
            >
              {Object.entries(categories).map(([k, v]) => (
                <option key={k} value={k}>
                  {v}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="label">Amount (£)</label>
            <input
              name="amount"
              type="number"
              step="0.01"
              inputMode="decimal"
              className="input"
              defaultValue={item.amount}
              required
            />
          </div>
          <div className="sm:col-span-2">
            <label className="label">Description</label>
            <input
              name="description"
              className="input"
              defaultValue={item.description}
              placeholder="e.g. New weeding tool, diesel, PLI premium"
            />
          </div>
          <div>
            <label className="label">Date</label>
            <input
              name="date"
              type="date"
              className="input"
              defaultValue={item.dateInput}
            />
          </div>
          {!item.isCopy && (
            <div>
              <label className="label">Repeats</label>
              <select
                name="recurrence"
                className="input"
                defaultValue={item.recurrence}
              >
                {Object.entries(repeatLabel).map(([k, v]) => (
                  <option key={k} value={k}>
                    {v}
                  </option>
                ))}
              </select>
            </div>
          )}
          <div className="flex items-end gap-2 sm:col-span-2">
            <button type="submit" className="btn-primary !py-2 !text-sm">
              Save changes
            </button>
            <button
              type="button"
              onClick={() => setEditing(false)}
              className="btn-ghost !py-2 !text-sm"
            >
              Cancel
            </button>
          </div>
          {item.isCopy ? (
            <p className="text-xs text-stone-400 sm:col-span-2">
              This one was added by a repeating cost. Editing it changes this
              entry only.
            </p>
          ) : (
            repeats && (
              <p className="text-xs text-stone-400 sm:col-span-2">
                Changes apply here and to future repeats. Entries already logged
                keep what you actually paid. Set Repeats to One-off to stop it.
              </p>
            )
          )}
        </form>
      )}
    </div>
  );
}
